-- where
SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE*fo.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT fp 
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT FROM FOOD_ORDER 
      WHERE LEFT(PRODUCE_DATE, 7) = '2022-05'
      GROUP BY PRODUCT_ID 
     ) fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;