WITH RECURSIVE TEMP AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR+1 FROM TEMP WHERE HOUR<23)
  
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT FROM
TEMP LEFT JOIN ANIMAL_INS
ON TEMP.HOUR = HOUR(ANIMAL_INS.DATETIME)

GROUP BY HOUR;