-- 코드를 입력하세요
SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES 
FROM REST_INFO ri JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MFAVORITES FROM REST_INFO
    GROUP BY FOOD_TYPE
) T
ON T.MFAVORITES = ri.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;